In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.1


In [3]:
if torch.cuda.is_available():
    print("cuda available")
    print("device name:",torch.cuda.get_device_name())

cuda available
device name: NVIDIA GeForce RTX 4050 Laptop GPU


## creating tensors 


In [4]:
# using empty
#  create memroy space (allocate a memory )
a=torch.empty(2,3)
type(a)
a

tensor([[2.5530e+38, 1.3088e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [5]:
# zeros
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [6]:
# uisng one 
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [7]:
# using rand
torch.rand(2,2)

tensor([[0.9313, 0.1889],
        [0.7922, 0.4461]])

In [8]:
# manual_seed  : for a same output for every time use a manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
# using a tensor
torch.tensor([[1,2,2],[5,6,6]])

tensor([[1, 2, 2],
        [5, 6, 6]])

# other ways

In [10]:
#  arrange : provide a one raneg and also provide a ste_ jump

print("using arange ->",torch.arange(0,10))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [11]:
# usinf linspace :for evanlly spce value we can use  a linespace
print("using linspace ->",torch.linspace(0,10,10))

using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [18]:
#  using eye : eye for identity matrix
print("using ye ->",torch.eye(5))

using ye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [19]:
#  using full : full used for a each items will be  5 value , also pass  a size of matrix 
print("using ye ->",torch.full((5,2),5))

using ye -> tensor([[5, 5],
        [5, 5],
        [5, 5],
        [5, 5],
        [5, 5]])


# tensors shapes

In [21]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
x.shape  # fild a shape of tensors 

torch.Size([2, 3])

In [28]:
# empty_like:  for some time u can create(need) a same size of tensors to copy items
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [29]:
# similar for a Zeros_like
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [32]:
#  for 1
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [31]:
#  in x tensors we can pass a int so error will arrived 
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'