In [1]:
import torch

#   tensor data type 

In [3]:
x=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
x.dtype

torch.int64

In [9]:
#  assign  data type
torch.tensor([1.0,2.0],dtype=torch.int32)

C:\Users\Vandan Patel\AppData\Local\Temp\ipykernel_764\3968532395.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  torch.tensor([1.0,2.0],dtype=torch.int32)


tensor([1, 2], dtype=torch.int32)

In [10]:
#  assign  data type
torch.tensor([1,2,3],dtype=torch.float16)
                            #  also float32 float64 

tensor([1., 2., 3.], dtype=torch.float16)

In [13]:
#  using to ()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [15]:
torch.rand_like(x,dtype=float)

tensor([[0.8004, 0.5459, 0.9053],
        [0.5096, 0.3076, 0.0472],
        [0.2935, 0.1158, 0.1248]], dtype=torch.float64)

# mathemtical operation 

In [26]:
x=torch.tensor([[1,1,1],[1,1,1],[2,2,2]])
#  addition 
print(" addition ->",x+1)
print(" subtraction ->",x-1)
print(" multiplication ->",x*5)
print(" division ->",x/2)
print(" power  ->",x**2)
print(" mod ->",x%2)



 addition -> tensor([[2, 2, 2],
        [2, 2, 2],
        [3, 3, 3]])
 subtraction -> tensor([[0, 0, 0],
        [0, 0, 0],
        [1, 1, 1]])
 multiplication -> tensor([[ 5,  5,  5],
        [ 5,  5,  5],
        [10, 10, 10]])
 division -> tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000],
        [1.0000, 1.0000, 1.0000]])
 power  -> tensor([[1, 1, 1],
        [1, 1, 1],
        [4, 4, 4]])
 mod -> tensor([[1, 1, 1],
        [1, 1, 1],
        [0, 0, 0]])


In [30]:
# abs valu
c=torch.tensor([1,-2,-5])
torch.abs(c)

tensor([1, 2, 5])

In [31]:
# negative
torch.neg(c)

tensor([-1,  2,  5])

In [40]:

d=torch.tensor([1.5,1.3,1.9,1.6,1.5,2.3,0.096])
print("round ->",torch.round(d))
print("ceil ->",torch.ceil(d))
print("floor ->",torch.floor(d))
print("clamp ->",torch.clamp(d,min=0,max=1))


round -> tensor([2., 1., 2., 2., 2., 2., 0.])
ceil -> tensor([2., 2., 2., 2., 2., 3., 1.])
floor -> tensor([1., 1., 1., 1., 1., 2., 0.])
clamp -> tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 0.0960])


# reduction operation

In [68]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e.type

<function Tensor.type>

In [69]:
# sum 
torch.sum(e)

tensor(34.)

In [73]:
print("sum along with row and column")
print("\n")
print("sum along with column",torch.sum(e,dim=0))
print("sum along with row",torch.sum(e,dim=1))
print("\n")
print("mean based on column",torch.mean(e,dim=0))
print("mean based on row",torch.mean(e,dim=1))



sum along with row and column


sum along with column tensor([13.,  9., 12.])
sum along with row tensor([24., 10.])


mean based on column tensor([6.5000, 4.5000, 6.0000])
mean based on row tensor([8.0000, 3.3333])


In [75]:
print("median based on column",torch.median(e,dim=0))
print("median based on row",torch.median(e,dim=1))


median based on column torch.return_types.median(
values=tensor([6., 0., 4.]),
indices=tensor([1, 1, 1]))
median based on row torch.return_types.median(
values=tensor([8., 4.]),
indices=tensor([2, 2]))


In [80]:
print("max based on column",torch.max(e,dim=0))
print("max based on row",torch.max(e,dim=1))
#  also calculate the min (minimum){ torch.min(e,dim={0/1})}

max based on column torch.return_types.max(
values=tensor([7., 9., 8.]),
indices=tensor([0, 0, 0]))
max based on row torch.return_types.max(
values=tensor([9., 6.]),
indices=tensor([1, 0]))


In [81]:
print("max based on column",torch.var(e,dim=0))
print("max based on row",torch.var(e,dim=1))

max based on column tensor([ 0.5000, 40.5000,  8.0000])
max based on row tensor([1.0000, 9.3333])


In [85]:
e

tensor([[7., 9., 8.],
        [6., 0., 4.]])

In [87]:
print(torch.argmin(e)) # give a position of a min 
print(torch.argmax(e))

tensor(4)
tensor(1)


# matrix multiplication


In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
