# comparision operator

In [1]:
import torch


In [2]:
i=torch.randint(0, 10, (2, 3))
j=torch.randint(0, 10, (2, 3))

In [3]:
print(i)
print(j)

tensor([[3, 7, 3],
        [7, 5, 6]])
tensor([[8, 1, 3],
        [2, 7, 5]])


In [5]:
#  greater than
print(i > j)
# greater than or equal to
print(i >= j)
# less than
print(i < j)
# less than or equal to
print(i <= j)
# equal to
print(i == j)
# not equal to
print(i != j)

tensor([[False,  True, False],
        [ True, False,  True]])
tensor([[False,  True,  True],
        [ True, False,  True]])
tensor([[ True, False, False],
        [False,  True, False]])
tensor([[ True, False,  True],
        [False,  True, False]])
tensor([[False, False,  True],
        [False, False, False]])
tensor([[ True,  True, False],
        [ True,  True,  True]])


In [7]:
print(i)
print(j)

tensor([[3, 7, 3],
        [7, 5, 6]])
tensor([[8, 1, 3],
        [2, 7, 5]])


In [6]:
# element-wise comparison
print(torch.eq(i, j))
# element-wise comparison
print(torch.ne(i, j))
# element-wise comparison
print(torch.gt(i, j))
# element-wise comparison
print(torch.ge(i, j))
# element-wise comparison
print(torch.lt(i, j))
# element-wise comparison
print(torch.le(i, j))
# element-wise comparison
print(torch.eq(i, j))
# element-wise comparison

tensor([[False, False,  True],
        [False, False, False]])
tensor([[ True,  True, False],
        [ True,  True,  True]])
tensor([[False,  True, False],
        [ True, False,  True]])
tensor([[False,  True,  True],
        [ True, False,  True]])
tensor([[ True, False, False],
        [False,  True, False]])
tensor([[ True, False,  True],
        [False,  True, False]])
tensor([[False, False,  True],
        [False, False, False]])


# special function

In [8]:
print("log ->",torch.log(i))

log -> tensor([[1.0986, 1.9459, 1.0986],
        [1.9459, 1.6094, 1.7918]])


In [9]:
print("exp ->",torch.exp(i))


exp -> tensor([[  20.0855, 1096.6332,   20.0855],
        [1096.6332,  148.4132,  403.4288]])


In [10]:
print("abs ->",torch.abs(i))


abs -> tensor([[3, 7, 3],
        [7, 5, 6]])


In [11]:
print("sqrt ->",torch.sqrt(i))

sqrt -> tensor([[1.7321, 2.6458, 1.7321],
        [2.6458, 2.2361, 2.4495]])


In [13]:
print("sin ->",torch.sin(i))


sin -> tensor([[ 0.1411,  0.6570,  0.1411],
        [ 0.6570, -0.9589, -0.2794]])


In [17]:
# print("cos ->",torch.cos(i))
print("tan ->",torch.tan(i))
print("sigmoid ->",torch.sigmoid(i))


tan -> tensor([[-0.1425,  0.8714, -0.1425],
        [ 0.8714, -3.3805, -0.2910]])
sigmoid -> tensor([[0.9526, 0.9991, 0.9526],
        [0.9991, 0.9933, 0.9975]])


In [18]:
print("relu ->",torch.relu(i))

relu -> tensor([[3, 7, 3],
        [7, 5, 6]])


In [19]:
i=torch.randint(0, 10, (2, 3),dtype=torch.float32)

In [22]:
print("softmax ->",torch.softmax(i,dim=0))
print("log_softmax ->",torch.log_softmax(i,dim=1))
print("tanh ->",torch.tanh(i))
print("relu ->",torch.relu(i))
print("selu ->",torch.selu(i))
print("hardshrink ->",torch.hardshrink(i))

softmax -> tensor([[0.8808, 0.1192, 0.9975],
        [0.1192, 0.8808, 0.0025]])
log_softmax -> tensor([[-0.1328, -5.1328, -2.1328],
        [-0.3151, -1.3151, -6.3151]])
tanh -> tensor([[1.0000, 0.9951, 1.0000],
        [1.0000, 0.9999, 0.0000]])
relu -> tensor([[8., 3., 6.],
        [6., 5., 0.]])
selu -> tensor([[8.4056, 3.1521, 6.3042],
        [6.3042, 5.2535, 0.0000]])
hardshrink -> tensor([[8., 3., 6.],
        [6., 5., 0.]])
