# copying tensor 

In [1]:
import torch

In [2]:
a=torch.randn(2,3)
a

tensor([[-0.6676,  0.2997, -1.1823],
        [-2.2083, -0.2049,  0.1088]])

In [4]:
b=a # copy by reference

In [5]:
a[0][0]=0

In [6]:
b

tensor([[ 0.0000,  0.2997, -1.1823],
        [-2.2083, -0.2049,  0.1088]])

In [7]:
id(a),id(b)

(2742476668336, 2742476668336)

In [8]:
b=a.clone() # copy by value

In [9]:
a[0][0]=1

In [10]:
a

tensor([[ 1.0000,  0.2997, -1.1823],
        [-2.2083, -0.2049,  0.1088]])

In [11]:
b

tensor([[ 0.0000,  0.2997, -1.1823],
        [-2.2083, -0.2049,  0.1088]])

In [12]:
id(a),id(b)

(2742476668336, 2744166378688)