In [1]:
import torch

In [3]:
torch.cuda.is_available() 

True

In [5]:
device=torch.device('cuda')
device

device(type='cuda')

In [7]:
torch.rand((2,3),device=device)

tensor([[0.1024, 0.5697, 0.6155],
        [0.7316, 0.1988, 0.9060]], device='cuda:0')

In [8]:
#  move tensor to cpu
t=torch.rand((2,3))
t

tensor([[0.3826, 0.5850, 0.0704],
        [0.9356, 0.6198, 0.9423]])

In [11]:
v=t.to(device)
v

tensor([[0.3826, 0.5850, 0.0704],
        [0.9356, 0.6198, 0.9423]], device='cuda:0')

In [13]:
v+5

tensor([[5.3826, 5.5850, 5.0704],
        [5.9356, 5.6198, 5.9423]], device='cuda:0')

In [16]:
import time
size=10000

# create a random tensor on cpu
matrix_cpu1=torch.rand(size,size)
matrix_cpu2=torch.rand(size,size)

# measure time to multiply on cpu
start=time.time()
result=torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time=time.time()-start

print(f"Time on cpu: {cpu_time} seconds")

# moving tensors to gpu
matrix_cuda1=matrix_cpu1.to("cuda")
matrix_cuda2=matrix_cpu2.to("cuda")
# measure time to multiply on gpu
start=time.time()
result=torch.matmul(matrix_cuda1,matrix_cuda2)
gpu_time=time.time()-start
print(f"Time on gpu: {gpu_time} seconds")

Time on cpu: 5.564979076385498 seconds
Time on gpu: 0.0411076545715332 seconds
