In [1]:
import numpy as np
import torch

In [2]:
a=torch.tensor([1,2,3,4,5])
a

tensor([1, 2, 3, 4, 5])

In [3]:
b=a.numpy()
b

array([1, 2, 3, 4, 5])

In [4]:
type(a),type(b) 

(torch.Tensor, numpy.ndarray)

In [5]:
c=np.array([1,2,3,4,5])
c

array([1, 2, 3, 4, 5])

In [6]:
torch.from_numpy(c)


tensor([1, 2, 3, 4, 5])