# inplace operation

In [1]:
import torch

In [4]:
i=torch.rand((2, 3))
j=torch.rand((2, 3))
print(i)
print(j)

tensor([[0.3540, 0.6141, 0.9383],
        [0.4166, 0.7017, 0.9357]])
tensor([[0.6895, 0.1774, 0.2704],
        [0.0022, 0.8824, 0.3225]])


In [7]:
i+j
#  new  tensor is  created  and  returned  as  the  result  of  the  addition  operation , occupying  a  new  memory  location

tensor([[1.0435, 0.7915, 1.2087],
        [0.4188, 1.5842, 1.2582]])

In [8]:
i.add_(j)

tensor([[1.0435, 0.7915, 1.2087],
        [0.4188, 1.5842, 1.2582]])

In [10]:
i # the  original  tensor  is  modified  in  place  by  the  addition  operation

tensor([[1.0435, 0.7915, 1.2087],
        [0.4188, 1.5842, 1.2582]])

In [12]:
j

tensor([[0.6895, 0.1774, 0.2704],
        [0.0022, 0.8824, 0.3225]])

In [13]:
torch.relu(i)

tensor([[1.0435, 0.7915, 1.2087],
        [0.4188, 1.5842, 1.2582]])

In [15]:
i.relu_() # in-place operation

tensor([[1.0435, 0.7915, 1.2087],
        [0.4188, 1.5842, 1.2582]])

In [16]:
i

tensor([[1.0435, 0.7915, 1.2087],
        [0.4188, 1.5842, 1.2582]])

In [ ]:
# _ at the end of the function name indicates that the operation is performed in-place operation