In [32]:
import torch


In [33]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
# reshape
a.reshape(2,2,2,2) # original shape is 4x4=16, new shape is 2x2x2x2=16

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [35]:
a.flatten() # flatten the tensor to 1D


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [36]:
b=torch.rand(2,3,4)
b

tensor([[[0.2153, 0.5531, 0.6625, 0.5377],
         [0.9125, 0.4928, 0.4607, 0.9776],
         [0.8886, 0.5158, 0.4645, 0.9233]],

        [[0.9260, 0.4753, 0.5356, 0.8635],
         [0.9096, 0.0411, 0.4291, 0.7254],
         [0.9276, 0.3592, 0.7975, 0.6149]]])

In [41]:
# permute
print(b.shape)
# change the order of dimensions of a tensor without changing the data itself 
print(b.permute(1,0,2)) # (2,3,4) index[0,1,2]-> index(1,0,2) [3,2,4]
print(b.permute(1,0,2).shape) 

torch.Size([2, 3, 4])
tensor([[[0.2153, 0.5531, 0.6625, 0.5377],
         [0.9260, 0.4753, 0.5356, 0.8635]],

        [[0.9125, 0.4928, 0.4607, 0.9776],
         [0.9096, 0.0411, 0.4291, 0.7254]],

        [[0.8886, 0.5158, 0.4645, 0.9233],
         [0.9276, 0.3592, 0.7975, 0.6149]]])
torch.Size([3, 2, 4])


In [42]:
# unsqueeze
# image size
d=torch.rand(226,226,3)

In [46]:
# print(d.unsqueeze(0)) # add a dimension at the beginning
print(d.unsqueeze(0).shape) # (1,226,226,3)

#  use of unsqueeze in CNN:  add a batch, channel dimension , and then height and width dimension 



torch.Size([1, 226, 226, 3])


In [47]:
d=torch.rand(1,20)
d

tensor([[0.8627, 0.1521, 0.3447, 0.7943, 0.5241, 0.3751, 0.9634, 0.0288, 0.3225,
         0.8857, 0.2599, 0.8076, 0.7266, 0.2750, 0.2481, 0.4852, 0.2123, 0.7807,
         0.7691, 0.4897]])

In [49]:
# squeeze
# remove the dimension of size 1
print(d.squeeze(0)) # remove the first dimension of size 1
print(d.squeeze(0).shape) 

tensor([0.8627, 0.1521, 0.3447, 0.7943, 0.5241, 0.3751, 0.9634, 0.0288, 0.3225,
        0.8857, 0.2599, 0.8076, 0.7266, 0.2750, 0.2481, 0.4852, 0.2123, 0.7807,
        0.7691, 0.4897])
torch.Size([20])
