
#### The NN module
* The `torch.nn` module in PyTorch is a core library that provides:
    - Pre-built layers
    - Loss functions
    - Activation functions
    - Other utilities

* It abstracts the complexity of creating and training neural networks, enabling you to focus on designing and experimenting with model architectures.
---
Key Components of torch.nn:
---
- **Modules (Layers)**:
    - `nn.Module`: The base class for all neural network modules. Your custom models and layers should subclass this class.
    - Common Layers: Includes layers like `nn.Linear` (fully connected layer), `nn.Conv2d` (convolutional layer), `nn.LSTM` (recurrent layer), and many others.
- **Activation Functions**:
    - Functions like `nn.ReLU`, `nn.Sigmoid`, and `nn.Tanh` introduce non-linearities to the model, allowing it to learn complex patterns.
- **Loss Functions**:
    - Provides loss functions such as `nn.CrossEntropyLoss`, `nn.MSELoss`, and `nn.NLLLoss` to quantify the difference between the model's predictions and the actual targets.
- **Container Modules**:
    - `nn.Sequential`: A sequential container to stack layers in order.
- **Regularization and Dropout**:
    - Layers like `nn.Dropout` and `nn.BatchNorm2d` help prevent overfitting and improve the model's ability to generalize to new data.Key Components of torch.nn:
 

### 1.simple NN model perceptron

In [42]:
import torch
import torch.nn as nn

In [43]:
class MyModel(nn.Module):
    def __init__(self, input_feature):
        super().__init__()
        self.linear = nn.Linear(input_feature, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,feature):
        out=self.linear(feature)
        out=self.sigmoid(out)
        return out

In [44]:
# create a data set 
feature=torch.rand(10,5)
# create a model
model=MyModel(feature.shape[1])
# call model for forward pass
model(feature)  # this will call forward function because of __call__ function in nn.Module class



tensor([[0.4541],
        [0.4923],
        [0.5502],
        [0.4923],
        [0.4979],
        [0.5361],
        [0.5399],
        [0.4384],
        [0.5263],
        [0.4536]], grad_fn=<SigmoidBackward0>)

In [45]:
#  show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.4217, -0.3088, -0.1235, -0.3255,  0.4284]], requires_grad=True)

In [46]:
model.linear.bias

Parameter containing:
tensor([-0.0061], requires_grad=True)

In [47]:
from torchinfo import summary

In [48]:
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
MyModel                                  [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### 2.NN model 
1. 5 input node,
2. 3 hidden node-relu,
3. 1 output node-sigmoid


In [49]:
class Model(nn.Module):
    def __init__(self, num_feature):
        super().__init__()
        self.linear1 = nn.Linear(num_feature, 3)
        self.relu=nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
    def forward(self, x):
        x = self.linear1(x)
        x=self.relu(x)
        x = self.linear2(x)
        x = self.sigmoid(x)
        return x

In [50]:
# create a data set 
feature=torch.rand(10,5)
# create a model
M=Model(feature.shape[1])
# call model for forward pass
M(feature)  # this will call forward function because of __call__ function in nn.Module class



tensor([[0.5158],
        [0.5198],
        [0.4929],
        [0.4855],
        [0.4647],
        [0.4697],
        [0.4476],
        [0.4662],
        [0.4647],
        [0.4647]], grad_fn=<SigmoidBackward0>)

In [51]:
M.linear1.weight



Parameter containing:
tensor([[ 0.3964,  0.1857,  0.1789, -0.3187, -0.1423],
        [ 0.2935, -0.2449, -0.3288,  0.3886, -0.2425],
        [-0.3004, -0.0217, -0.0841, -0.2912, -0.0376]], requires_grad=True)

In [52]:
M.linear2.weight


Parameter containing:
tensor([[ 0.5638, -0.1067, -0.4889]], requires_grad=True)

In [53]:
M.linear2.bias

Parameter containing:
tensor([-0.1416], requires_grad=True)

In [54]:
M.linear1.bias

Parameter containing:
tensor([ 0.0577, -0.1911,  0.3462], requires_grad=True)

In [55]:
summary(M, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### 3.use a squential model to build NN

In [56]:
class Model(nn.Module):
    def __init__(self, num_feature):
        super().__init__()
        self.Network = nn.Sequential(
            nn.Linear(num_feature, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()

        )
    def forward(self, x):
        x = self.linear1(x)
        x=self.relu(x)
        x = self.linear2(x)
        x = self.sigmoid(x)
        return x

In [57]:
#  imporve the training pipeline